services:
  - type: web
    name: wrestling-news-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: wrestling-news-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: wrestling-news-db
    databaseName: wrestling_news
    user: wrestling_news_user
